<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file=".py" name="TestFibonaaci-20190710130639" skipped="0" tests="3" time="0.006" timestamp="2019-07-10T13:06:39">
	<testcase classname="TestFibonaaci" file="test_fibonacci_pytest.py" line="14" name="test_compute_large_fib" time="0.005" timestamp="2019-07-10T13:06:39">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="TestFibonaaci" file="test_fibonacci_pytest.py" line="11" name="test_compute_small_fib" time="0.000" timestamp="2019-07-10T13:06:39">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="TestFibonaaci" file="test_fibonacci_pytest.py" line="17" name="test_invalid_int_arg" time="0.001" timestamp="2019-07-10T13:06:39">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
